<?php

$to = $_POST["to"];
//$to = "nidhipkathiriya@gmail.com";
$subject = "Car details";

$message = "
<html>
<head>
<title>Car dekho</title>
</head>
<body>
<p>This email is autogenerated!</p>
<p>Our staff will reachout to you within next 24hrs</p>
</body>
</html>
";

// Always set content-type when sending HTML email
$headers = "MIME-Version: 1.0" . "\r\n";
$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

// More headers
$headers .= 'From: <BigBoyzToyZ@car.com>' . "\r\n";
$headers .= 'Cc: myboss@example.com' . "\r\n";

mail($to,$subject,$message,$headers);
?>